name: Web Bundle Analysis
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

permissions:
  contents: read
  actions: read
  pull-requests: write # for comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: true

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build
        run: pnpm turbo run build --filter=web

      - name: Analyze bundle
        run: npx @makeswift/nextjs-bundle-diff@latest analyze --rootDirectory=.
        working-directory: ./apps/web

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ./apps/web/.next/analyze/__bundle_analysis.json

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: asdf.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: ./apps/web/.next/analyze/base

      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR ./.next/analyze/base && npx @makeswift/nextjs-bundle-diff@latest compare --rootDirectory=. --fileA=./.next/analyze/base/bundle/__bundle_analysis.json --fileB=./.next/analyze/__bundle_analysis.json
        working-directory: ./apps/web

      - name: Get Comment Body
        id: get-comment-body
        if: success() && github.event.number
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat ./apps/web/.next/analyze/__bundle_comparison_comment.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __NEXTJS_BUNDLE_DIFF -->'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
